language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  # For some reason Travis' build envs have wildly different pip/setuptools
  # versions between minor Python versions, and this can cause many hilarious
  # corner packaging cases. So...
  - pip install -U pip
  # Setuptools 34+ seems to get less stable
  - pip install 'setuptools>33,<34'
  # Install dev requirements && sanity print
  - pip install -r dev-requirements.txt
  - pip list --format=columns
  # Dev tooling sanity test: can invoke list tasks?
  - inv --list
script:
  # We have no real tests at present so we just make sure installation works,
  # first off.
  - pip install .
  # Websites build OK? (Not on PyPy3, Sphinx is all "who the hell are you?" =/
  - "[[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]] && inv docs"
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
