version: 2.1

orbs:
  orb: invocations/orb@1.3.0


jobs:

  compat:
    parameters:
      python:
        type: string
      sphinx:
        type: string
    executor:
      name: orb/default
      version: "<< parameters.python >>"
    steps:
      - orb/setup
      # Nuke ourselves and sphinx, for some cleanliness. (Ideal: a way to
      # install dev deps + some other tweak, in the same step; can pip do
      # that?)
      - run: "pip uninstall -y alabaster sphinx"
      # Get Sphinx under test, and then reinstall ourselves
      - run: "pip install -U sphinx==<< parameters.sphinx >>"
      - run: "pip install ."
      - run: "pip list --format=columns"
      # Make sure we can run (building our own docs, as we dogfood) w/o
      # exploding.
      # TODO: some suite of canaries to check for in the rendered html? How are
      # other themes/plugins testing themselves?
      - run: "inv docs"
      - orb/debug


workflows:
  main:
    jobs:
      # These will all happen under Python 3.6 by default
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - orb/test-release:
          name: Release test
      - orb/docs:
          name: Docs
      # We have no tests to matrix, and this is too niche for the orb, so just
      # do a bunch of install/run tests on different Python and Sphinx versions
      # for compat testing.
      - compat:
          name: "Docs (Py<< matrix.python >>/Sphinx << matrix.sphinx >>)"
          # May as well not burn a lot of credits if something is seriously
          # busted.
          requires: ["Docs"]
          matrix:
            parameters:
              python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
              # TODO: still need to find a way to solve escaping hell on circle
              # re: parameters containing >< symbols
              sphinx:
                - "1.6.7"
                - "1.7.9"
                - "1.8.6"
                - "2.4.5"
                - "3.5.4"
                - "4.5.0"
                - "5.3.0"
                - "6.1.3"
            exclude: []
